# All settings 

# Topics
ros:
  topics:
    gps: "/ublox_gps_node/fix"
    odom: "/robot_odom"
    image: "/neural_depth/left/image_rect_raw/compressed"
  
  # Queue sizes for subscribers (buffer incoming messages)
  queue_size: 10

# WebSocket Server
websocket:
  host: "localhost"
  port: 8765
  update_rate_hz: 10  # Send data to frontend: real-time visualization

# Data Management
data:
  path_buffer_size: 100  # Keep last 100 GPS points for path visualization: ~25 sec of GPS history at 4Hz (smooth, lightweight)
  enable_images: false    # Set to true to process camera images (heavy)
  image_throttle: 2         # Send only 2 images/sec (not all 13)


# Logging
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/robot_monitor.log"
  console: true
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
